### ISSUE TITLE
Loading FMOD in Project

### ISSUE THREAD

**Issue by MondayHopscotch** [NateAustin/fmod-jni#2]
I stumbled across this project after having used FMOD in some unity work I did for game jams. I'm currently working on a game in libGDX and found your project, but I have having trouble understanding why its not working for me.

Versions:
```
FMOD Studio API v1.10.13
IntelliJ Ultimate 2019.1.2
libGDX 1.6.1 (I used the latest setup app to generate the project)
```

I believe I hit all the right dll files. I am only intending to build for Windows right now:
![image](https://user-images.githubusercontent.com/3443665/57978418-d5460000-79ca-11e9-9698-8fc4037375c6.png)

I built the `fmod-jni-jar.jar` file via the IntelliJ Ant Build menu:
![image](https://user-images.githubusercontent.com/3443665/57978426-ff97bd80-79ca-11e9-81ca-ce63bcd8e189.png)

The output looks like this:
![image](https://user-images.githubusercontent.com/3443665/57978448-6ddc8000-79cb-11e9-9150-c2f016ed7908.png)

I put the built jar into my project, but when calling `FMODLoader.loadNatives()` it is returning `false`. I don't see any output as to why. I'm not sure how to verify the jar was built correctly. The classes seem to be there, as my auto-complete is correctly seeing all of the classes and functions.

Looking at the code, it appears that if it is failing to load DLL files, it would print that to the output, but I haven't seen any log messages come out of the call to `loadNatives()`

**Comment by NateAustin** [comment]
Hmm, yeah that's strange. One thing I notice is that you're including the logging dlls as well. Those aren't needed, but I don't see why they would break anything. Our libgdx version is 1.9.12 I think, but again I don't expect that to matter since fmod-jni doesn't depend on libgdx. The other versions look correct. 

Here's what my jar looks like:
![image](https://user-images.githubusercontent.com/6526816/57982930-6770f700-7a11-11e9-90ec-71363920c67d.png)

You can try dropping a breakpoint and stepping in to the load method. That might shed some light.

You can also grab the jar from Wildermyth to compare, since that is definitely working. I'm not posting it only because I don't want to worry about legal issues with including FMOD binaries, since they have a developer license you need to agree to. But you've already agreed to those, nate dot austin at gmail dot com and I can help you out.

**Comment by MondayHopscotch** [comment]
Interesting. The built jar I have definitely doesn't have the top-level folder like that. Mind looks like:
![image](https://user-images.githubusercontent.com/3443665/57984201-b2413d80-7a16-11e9-9a0d-12ee757da884.png)

One other weird thing I'm noticing is that yours is called `fmod-jni.jar` while mine is `fmod-jni-jar.jar`. Not sure if that means anything.

Also, I am actually on libGDX version `1.9.9`. I was looking at the wrong thing.

It's interesting that if all the actual DLL files are missing from the jar that I'm not seeing any output regarding missing files. But I might be mistaken about how the fmod loader class is operating. I will do some debugging to see what's happening in the loader class, but all of the DLL's being missing in the jar is surely problematic.

**Comment by NateAustin** [comment]
Yep, certainly seems like a build-script problem or similar. Let me know what you find and I'll improve the build script / docs / logging.

**Comment by MondayHopscotch** [comment]
Can you point me to where in the `antBuild.xml` file you are referencing the files in `fmod_runtimes`? I haven't been able to track down how the `.dll` files are being added into the `.jar` file.

 I've been trying to dig into how the build works. I'm pretty rusty with ant builts, but I don't actually see anything that is referencing the `fmod_runtimes` other than the `CMakeLists.txt`. Those are in the `linux_clion`, so I assume those aren't my concern since I'm only working in Windows.

**Comment by NateAustin** [comment]
Hey, I'm sorry, it looks like the build script in there was an old version. I was building using the IDE's "artifact" feature and I forgot to update the ant build script when I changed the artifact definition. I've regenerated the ant script (fmod-jni.xml) and tested it, it makes a working jar now. Let me know if that doesn't solve the problem. So sorry and thanks for pointing it out!

**Comment by MondayHopscotch** [comment]
Things seem to be working now! I was able to build the jar, import it into my new project, and play events. Thanks!
