### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by SkyAphid** [NateAustin/fmod-jni#3]
Hi!

I'm extremely interested in this API, but is it still up to date? Will it work with newer versions of fmod? Before I invest time into it, I'd like to know the state of the project. I really do need an fmod solution for Java for my own game engine.

I'd love to hear back - my email is on my profile.
https://github.com/SkyAphid

Thank you for your time! I made an issue because I can't find any other way to contact you.

**Comment by NateAustin** [comment]
It's not up to date with FMOD Studio 2.0, sorry. It is still in use.

**Comment by SkyAphid** [comment]
Hi again, sorry for the late reply.

Do you intend to ever update it?

**Comment by NateAustin** [comment]
I don't have plans to update it (since we're moving away from java for our next projects), sorry.
